const assert = require('node:assert/strict')
const { emptyCreativeForm, validateCreativeStep, creativeApplicationId, profiles, isWebUrl, isCreativeDetails, creativeDetails } = require(process.env.CREATIVE_MODULE || '/tmp/dosmicos-unit/creative.js')
;(async()=>{
  assert(Object.keys(validateCreativeStep(emptyCreativeForm,0)).length >= 6)
  for (const profile of profiles) assert.deepEqual(validateCreativeStep({...emptyCreativeForm,profile,full_name:'Nombre',email:'test@example.test',phone:'+57 300 1234567',university:'Otra universidad',program:'Comunicación'},0),{})
  for (const date of ['2026-10-31','2027-02-01','2026-11-31','invalid','']) assert(validateCreativeStep({...emptyCreativeForm,start_date:date},1).start_date)
  for (const date of ['2026-11-01','2027-01-31']) assert(!validateCreativeStep({...emptyCreativeForm,start_date:date},1).start_date)
  for (const url of ['javascript:alert(1)','data:text/html,x','https://user:pass@example.test','invalid']) assert(!isWebUrl(url))
  assert(isWebUrl('https://example.test/video'))
  assert.equal(await creativeApplicationId('TEST@example.test'),await creativeApplicationId(' test@example.test '))
  assert.notEqual(await creativeApplicationId('test@example.test'),await creativeApplicationId('other@example.test'))
  assert.match(await creativeApplicationId('test@example.test'),/^[a-f0-9]{8}-[a-f0-9]{4}-5[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/)
  assert(isCreativeDetails(creativeDetails(emptyCreativeForm)))
  for (const invalid of [null,{}, {version:'creative-2026-v1',works:null}, {...creativeDetails(emptyCreativeForm),works:[null,null]}]) assert(!isCreativeDetails(invalid))
  console.log('Validation: both profiles, date boundaries, invalid dates, unsafe links and stable submission identity PASS')
})().catch(e=>{console.error(e);process.exit(1)})
