const assert = require('node:assert/strict')
const {emptyCreativeForm,validateCreativeForm,creativeApplicationId,profiles,isWebUrl,isCreativeDetails,creativeDetails,achievementQuestion}=require(process.env.CREATIVE_MODULE || '/tmp/dosmicos-unit/creative.js')
;(async()=>{
 const required=validateCreativeForm(emptyCreativeForm)
 assert.deepEqual(Object.keys(required).sort(),['email','full_name','impressive_achievement','profile','resume_url','university','program'].sort())
 const valid={...emptyCreativeForm,full_name:'Nombre',email:'test@example.test',university:'Universidad local',program:'Carrera local',resume_url:'reference',impressive_achievement:'Logro local'}
 assert(validateCreativeForm({...valid,profile:profiles[0],university:'   '}).university)
 assert(validateCreativeForm({...valid,profile:profiles[0],program:'   '}).program)
 assert(isCreativeDetails({version:'creative-2026-brief-v2',profile:profiles[0]}))
 for(const profile of profiles)assert.deepEqual(validateCreativeForm({...valid,profile}),{})
 assert(validateCreativeForm({...valid,profile:profiles[0],resume_url:'',portfolio_link:'https://example.test/portfolio'}).resume_url)
 for(const url of ['javascript:alert(1)','data:text/html,x','https://user:pass@example.test','invalid'])assert(!isWebUrl(url))
 assert(isWebUrl('https://example.test/portfolio'))
 assert.deepEqual(creativeDetails({...valid,profile:profiles[0]}),{version:'creative-2026-brief-v2',profile:profiles[0],program:'Carrera local'})
 assert(isCreativeDetails(creativeDetails(valid)))
 for(const invalid of [null,{}, {version:'creative-2026-brief-v2',profile:{}},{version:'creative-2026-v1',works:null}])assert(!isCreativeDetails(invalid))
 assert.equal(achievementQuestion,'¿Qué es lo más impresionante que has construido, organizado o logrado FUERA de la universidad y de las notas académicas?')
 assert.equal(await creativeApplicationId('TEST@example.test'),await creativeApplicationId(' test@example.test '))
 assert.notEqual(await creativeApplicationId('test@example.test'),await creativeApplicationId('other@example.test'))
 assert.match(await creativeApplicationId('test@example.test'),/^[a-f0-9]{8}-[a-f0-9]{4}-5[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/)
 console.log('PASS: eight-field form, both profiles, CV required/portfolio optional, exact achievement question, unsafe links, stable identity and JSON guard')
})().catch(e=>{console.error(e);process.exit(1)})
