'use client'
import { CreativeForm, profiles } from '@/lib/creative'
interface Props { data: CreativeForm; update: (data: Partial<CreativeForm>) => void; errors: Record<string,string>; step: number; upload: (file: File) => void; uploading: boolean; fileName: string }
export default function CreativeFields({data, update, errors, step, upload, uploading, fileName}: Props) {
  function field(name: keyof CreativeForm, label: string, options?: string[], type = 'text', multiline = false) {
    const props = { id: name, name, value: data[name], onChange: (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => update({[name]: e.target.value}), 'aria-invalid': !!errors[name], 'aria-describedby': errors[name] ? `${name}-error` : undefined, className: `w-full min-w-0 px-4 py-3 rounded-lg border focus:outline-none focus:ring-2 focus:ring-neutral-700 ${errors[name] ? 'border-red-400 bg-red-50' : 'border-neutral-200 bg-white'}` }
    return <div key={name}><label htmlFor={name} className="block text-sm font-medium text-neutral-700 mb-2">{label}</label>{options ? <select {...props}><option value="">Selecciona una opción</option>{options.map(option => <option key={option}>{option}</option>)}</select> : multiline ? <textarea {...props} rows={3} maxLength={1000}/> : <input {...props} type={type} maxLength={type === 'date' ? undefined : 500} min={type === 'date' ? '2026-11-01' : undefined} max={type === 'date' ? '2027-01-31' : undefined} autoComplete={name === 'full_name' ? 'name' : name === 'email' ? 'email' : name === 'phone' ? 'tel' : undefined}/>} {errors[name] && <p id={`${name}-error`} className="text-red-600 text-sm mt-2">{errors[name]}</p>}</div>
  }
  return <div className="space-y-6">
    <div><h2 className="text-2xl md:text-3xl font-semibold tracking-tight">{['Tu perfil', 'Tu disponibilidad', 'Tus trabajos'][step]}</h2><p className="text-neutral-500 mt-2">{['Elige el perfil que más se parece a ti.', 'La duración se acuerda según tu universidad.', 'Comparte dos trabajos existentes: pueden ser académicos, personales o profesionales. La evaluación específica vendrá después.'][step]}</p></div>
    {step === 0 && <>{field('profile', 'Perfil al que te postulas', [...profiles])}{field('full_name', 'Nombre completo')}{field('email', 'Correo electrónico', undefined, 'email')}{field('phone', 'Teléfono / WhatsApp', undefined, 'tel')}{field('university', 'Universidad o institución')}{field('program', 'Programa académico')}</>}
    {step === 1 && <>{field('eligibility', '¿Tu universidad te habilita para realizar prácticas?', ['Sí, estoy habilitado/a', 'Pendiente de confirmar', 'No estoy habilitado/a'])}{field('start_date', 'Fecha disponible de inicio (noviembre 2026–enero 2027)', undefined, 'date')}{field('onsite', '¿Puedes asistir presencialmente en Bogotá?', ['Sí', 'Necesito conversar sobre mi disponibilidad', 'No'])}{field('schedule', 'Compatibilidad de lunes a viernes, 08:00–17:00, con descansos y según tu horario académico', ['Compatible con mis estudios', 'Necesito ajustes por estudios', 'No es compatible'])}{field('availability_notes', 'Horarios de clase, ajustes o requisitos pendientes (si aplica)', undefined, 'text', true)}</>}
    {step === 2 && <>
      {field('portfolio_link', 'Enlace a tu portafolio (CV o portafolio requerido; puedes incluir ambos)', undefined, 'url')}
      <div><label htmlFor="resume-upload" className="block text-sm font-medium text-neutral-700 mb-2">Hoja de vida — PDF o Word, máximo 5 MB</label><input id="resume-upload" type="file" accept=".pdf,.doc,.docx" disabled={uploading} onChange={e => { const file = e.target.files?.[0]; if (file) upload(file); e.target.value = '' }} className="block w-full text-sm file:mr-3 file:py-3 file:px-4 file:border-0 file:rounded-lg"/><p role="status" className="text-sm mt-2">{uploading ? 'Subiendo…' : data.resume_url ? `Archivo subido: ${fileName}` : ''}</p><p className="text-sm text-neutral-500 mt-2">Comparte solo material que puedas divulgar y evita datos personales de terceros.</p></div>
      {field('work1_url', 'Trabajo 1 — enlace', undefined, 'url')}{field('work1_contribution', 'Trabajo 1 — describe qué hiciste tú', undefined, 'text', true)}
      {field('work2_url', 'Trabajo 2 — enlace', undefined, 'url')}{field('work2_contribution', 'Trabajo 2 — describe qué hiciste tú', undefined, 'text', true)}
      <p className="text-sm text-neutral-500">Verifica que los enlaces permitan revisar el material. Al enviar, compartes esta información para el proceso de selección de prácticas de Dosmicos.</p>
    </>}
  </div>
}
